server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://localhost:3306/bookstore_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "3ZrguQexZQRXtCX8xXPICyhaGFgs6bhdpqrKSb8iQ491QvDsg0+mYDVOcmdFYjYu"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

app:
  services:
    profile: http://localhost:8081/profile